# app/config/routing.yml
BloggerBlogBundle_blog:
    pattern:  /blog
    defaults: { _controller: BloggerBlogBundle:Page:index }

BloggerBlogBundle_contact:
    pattern: /contact
    defaults: { _controller: BloggerBlogBundle:Page:contact }

BloggerBlogBundle_about:
    pattern: /about
    defaults: { _controller: BloggerBlogBundle:Page:about }

BloggerBlogBundle_homepage:
    pattern:  /blog/{name}
    defaults: { _controller: BloggerBlogBundle:Default:index }
user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

article:
    resource: "@ArticleBundle/Controller/"
    type:     annotation
    prefix:   /article

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
